system:
  host: "0.0.0.0"
  port: 8080
  name: "Microservice Template"
  version: "1.0"
  description: "A Go microservice template with PostgreSQL integration"
  timezone: "UTC"
repository:
  providers:
    - name: "postgres"
      enabled: true
      connection:
        host: "localhost"
        port: 5432
        dbName: "microservice_db"
        username: "pgadmin"
        password: "pgadmin"
      modules:
        - users