system:
  host: "0.0.0.0"
  port: 8080
  name: "Microservice Template"
  version: "1.0"
  description: "A Go microservice template with PostgreSQL integration"
  timezone: "UTC"
cache:
  enabled: true
  type: "redis"
  config:
    host: "redis-container"
    port: 6379
    password: ""
    db: 2
    ttl: 300 # Time to live in seconds (300seconds = 5 minutes)
repository:
  providers:
    - name: "postgres"
      enabled: true
      connection:
        host: "localhost"
        port: 5432
        dbName: "microservice_db"
        username: "pgadmin"
        password: "pgadmin"
      modules:
        - users