version: '3.8'

services:
  microservice:
    build:
      context: ..
      dockerfile: Dockerfile
    image: go-microservice-template:latest
    container_name: go-microservice
    ports:
      - "8282:8282"
    restart: unless-stopped
    # environment:
      # Add environment variables here if needed
      # EXAMPLE_ENV: value
    # Uncomment the following lines if you want to mount code for live reload (development only)
    # volumes:
    #   - ../:/app
